import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { useInsight } from '@/hooks/useInsight'
import type { MetricsSection } from '@/lib/api'

export function InsightPanel({ section }: { section: MetricsSection }) {
  const { data, isLoading, error, regenerate } = useInsight(section)

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="text-base">AI Insight</CardTitle>
        <Button
          variant="outline"
          size="sm"
          onClick={() => regenerate.mutate()}
          disabled={regenerate.isPending}
        >
          {regenerate.isPending ? 'Regenerating...' : 'Regenerate'}
        </Button>
      </CardHeader>
      <CardContent>
        {isLoading && <p className="text-sm text-muted-foreground">Loading...</p>}
        {error && <p className="text-sm text-destructive">Could not load the AI insight.</p>}
        {data && (
          <>
            <p className="whitespace-pre-line text-sm">{data.content}</p>
            <p className="mt-3 text-xs text-muted-foreground">
              Generated by {data.model} on {new Date(data.generated_at).toLocaleString('en-IE')}
            </p>
          </>
        )}
      </CardContent>
    </Card>
  )
}
