import type { ReactElement } from 'react'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { describe, expect, it, vi } from 'vitest'
import { InsightPanel } from './InsightPanel'
import { TooltipProvider } from '@/components/ui/tooltip'
import * as api from '@/lib/api'

vi.mock('@/lib/api', async () => {
  const actual = await vi.importActual<typeof import('@/lib/api')>('@/lib/api')
  return { ...actual, fetchInsight: vi.fn(), regenerateInsight: vi.fn() }
})

function renderWithProviders(ui: ReactElement) {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  return render(
    <QueryClientProvider client={queryClient}>
      <TooltipProvider>{ui}</TooltipProvider>
    </QueryClientProvider>,
  )
}

describe('InsightPanel', () => {
  it('shows a loading state, then the generated commentary', async () => {
    vi.mocked(api.fetchInsight).mockResolvedValue({
      section_key: 'profitability',
      content: 'Margins improved steadily across the two years shown.',
      model: 'gemini-2.5-flash',
      generated_at: '2026-07-04T12:00:00Z',
      prompt_version: 'v1',
    })

    renderWithProviders(<InsightPanel section="profitability" />)

    expect(screen.getByText('Loading...')).toBeInTheDocument()
    expect(
      await screen.findByText('Margins improved steadily across the two years shown.'),
    ).toBeInTheDocument()
    expect(screen.getByText(/generated on/i)).toBeInTheDocument()
    expect(screen.queryByText(/generated by gemini-2.5-flash/i)).not.toBeInTheDocument()

    const user = userEvent.setup()
    await user.hover(screen.getByRole('button', { name: /which ai model generated this/i }))

    expect(await screen.findByText(/generated by gemini-2.5-flash/i)).toBeInTheDocument()
  })

  it('shows an error state when the request fails', async () => {
    vi.mocked(api.fetchInsight).mockRejectedValue(new Error('network error'))

    renderWithProviders(<InsightPanel section="profitability" />)

    expect(await screen.findByText(/could not load the ai insight/i)).toBeInTheDocument()
  })

  it('replaces the content with a freshly regenerated version on click', async () => {
    vi.mocked(api.fetchInsight).mockResolvedValue({
      section_key: 'profitability',
      content: 'Original commentary.',
      model: 'gemini-2.5-flash',
      generated_at: '2026-07-04T12:00:00Z',
      prompt_version: 'v1',
    })
    vi.mocked(api.regenerateInsight).mockResolvedValue({
      section_key: 'profitability',
      content: 'Freshly regenerated commentary.',
      model: 'gemini-2.5-flash',
      generated_at: '2026-07-05T09:00:00Z',
      prompt_version: 'v1',
    })

    const user = userEvent.setup()
    renderWithProviders(<InsightPanel section="profitability" />)
    await screen.findByText('Original commentary.')

    await user.click(screen.getByRole('button', { name: /regenerate/i }))

    expect(await screen.findByText('Freshly regenerated commentary.')).toBeInTheDocument()
  })
})
